# Generated by Django 4.1 on 2022-09-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterField(
            model_name='directory',
            name='dir_path',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.location'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.SmallIntegerField(choices=[(1, 'Normal'), (2, 'Collection'), (3, 'Name'), (4, 'POI')], default=0),
        ),
    ]
