# Generated by Django 4.1 on 2022-08-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=16)),
                ('legal_name', models.CharField(blank=True, max_length=32, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=64, null=True)),
                ('usci', models.CharField(blank=True, max_length=32, null=True, verbose_name='Unified Social Credit Identifier')),
                ('company_size_min', models.IntegerField(blank=True, null=True)),
                ('company_size_max', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
            ],
        ),
        migrations.CreateModel(
            name='PostingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=16)),
                ('posting_platform', models.CharField(choices=[('zhipin', 'Boss Zhipin'), ('lagou', 'Lagou'), ('liepin', 'Liepin'), ('zhaopin', 'Zhilian Zhaopin')], max_length=16)),
                ('platform_id', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
            ],
            options={
                'verbose_name_plural': 'posting companies',
                'db_table': 'job_posting_company',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('posting_id', models.CharField(max_length=32)),
                ('posting_status', models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Closed')])),
                ('monthly_min', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_months', models.SmallIntegerField(default=12)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('poster_name', models.CharField(blank=True, max_length=8)),
                ('poster_id', models.CharField(blank=True, max_length=32)),
                ('head_hunter', models.CharField(blank=True, max_length=16)),
                ('posted_at', models.DateTimeField()),
                ('refreshed_at', models.DateTimeField()),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.position')),
                ('posting_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.postingcompany')),
            ],
        ),
    ]
